FROM node:12.16.3

ARG APP_HOST_ARG
ARG APP_PORT_ARG
ARG DB_HOST_ARG
ARG DB_PORT_ARG
ARG DB_NAME_ARG
ARG DB_USER_ARG
ARG DB_PASSWORD_ARG

WORKDIR /mep-api

ENV APP_HOST = $APP_HOST_ARG
ENV APP_PORT = $APP_PORT_ARG
ENV DB_HOST = $DB_HOST_ARG
ENV DB_PORT = $DB_PORT_ARG
ENV DB_NAME = $DB_NAME_ARG
ENV DB_USER = $DB_USER_ARG
ENV DB_PASSWORD = $DB_PASSWORD_ARG

COPY ["package.json", "package-lock.json" , "./"]

EXPOSE 8080/tcp

EXPOSE 8080/udp

RUN npm install -g nodemon

RUN npm install

COPY . .

CMD ["node","server.js"]