# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Med-Api CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      APP_HOST: ${{secret.APP_HOST}} 
      APP_PORT: ${{secret.APP_PORT}}
      DB_HOST:  ${{secret.DB_HOST}}
      DB_NAME:  ${{secret.DB_NAME}}
      DB_PORT:  ${{secret.DB_PORT}}
      DB_USER:  ${{secret.DB_USER}} 
      DB_PASSWORD:  ${{secret.DB_PASSWORD}}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
